[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "scheduling"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    'timefold == 1.22.1b0',
    'pytest == 8.2.2'
]


[project.scripts]
run-app = "scheduling:main"